users:
  name:
    max_length: 50
  email:
    max_length: 255
  password:
    min_length: 6
  limit: 10
css:
  gravatar:
    size: 80
  gravatar_index:
    size: 50
remember: "1"
config:
  production:
    host: "sample-app-hpk.herokuapp.com"
    address: "smtp.sendgrid.net"
    port: "587"
